# Generated by Django 3.2.16 on 2023-01-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=128)),
                ('phone_number', models.CharField(max_length=11)),
                ('favorite_movie', models.CharField(max_length=128)),
                ('date_joined', models.DateField()),
            ],
        ),
    ]
