# Generated by Django 3.2.16 on 2023-01-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='date_joined',
        ),
    ]
